[package]
name = "keccak256"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "keccak256"
path = "src/main.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
polkavm-derive = { path = "../../crates/polkavm-derive" }
simplealloc = { path = "../../crates/simplealloc" }