[profile.release]
lto = "fat"
panic = "abort"
opt-level = 3
codegen-units = 1
debug = true

[profile.no-lto]
inherits = "release"
lto = false

[workspace]
resolver = "2"
members = [
    "fib",
    "priviliged",
    "admin",
    "staking",
    "accounts",
    "tribonacci",
    "megatron",
    "test_export",
    "keccak256"
 #   "tokens",
, "sha256"]
